// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package feedpg

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updatePoliceEvent = `-- name: UpdatePoliceEvent :exec
insert into police_event (
  id,
  url,
  title,
  region,
  description,
  publish_time,
  create_time,
  revision
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
`

type UpdatePoliceEventParams struct {
	ID          uuid.UUID
	Url         string
	Title       string
	Region      string
	Description string
	PublishTime time.Time
	CreateTime  time.Time
	Revision    string
}

func (q *Queries) UpdatePoliceEvent(ctx context.Context, arg UpdatePoliceEventParams) error {
	_, err := q.db.ExecContext(ctx, updatePoliceEvent,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.Region,
		arg.Description,
		arg.PublishTime,
		arg.CreateTime,
		arg.Revision,
	)
	return err
}
