// Code generated by sqlc. DO NOT EDIT.

package feedpg

import (
	"time"

	"github.com/google/uuid"
)

type PoliceEvent struct {
	ID          uuid.UUID
	Url         string
	Title       string
	Region      string
	Description string
	PublishTime time.Time
	CreateTime  time.Time
	Revision    string
}
